Repository microsoft/coyote, pull requests merged in 2024-03, with the labels that each got.

#497 update the project to net8.0
  .config/dotnet-tools.json
  .github/workflows/codeql-analysis.yml
  .github/workflows/test-coyote.yml
  .github/workflows/test-performance.yml
  Common/build.props
  History.md
  Samples/CloudMessaging/run-mock.cmd
  Samples/CloudMessaging/run-nondeterminism.cmd
  Samples/CloudMessaging/run.cmd
  Samples/Common/TestDriver/rewrite.coyote.json
  Samples/Common/build.props
  Samples/README.md
  Samples/Scripts/run-tests.ps1
  Samples/WebApps/ImageGalleryAspNet/ImageGallery/design.dgml
  Samples/WebApps/ImageGalleryAspNet/ImageGallery/readme.md
  Samples/WebApps/ImageGalleryAspNet/rewrite.coyote.json
  Samples/WebApps/PetImagesAspNet/PetImages.Tests/PetImages.Tests.csproj
  Samples/WebApps/PetImagesAspNet/PetImages.Tests/rewrite.coyote.json
  Scripts/CI/azure-nuget-sign-publish.yml
  Scripts/common.psm1
  Scripts/gen-docs.ps1
  Scripts/run-benchmark-history.ps1
  Scripts/run-benchmarks.ps1
  Scripts/run-tests.ps1
  Source/Test/Rewriting/RewritingOptions.cs
  Source/Test/Rewriting/Types/Threading/Interlocked.cs
  Source/Test/Test.csproj
  Tests/compare-rewriting-diff-logs.ps1
  Tests/get-rewriting-diff-logs.ps1
  Tools/CLI/Coyote.CLI.csproj
  Tools/Coyote/Coyote.csproj
  docs/assets/images/RaftMocking.dgml
  docs/assets/images/RaftMocking.svg
  docs/assets/images/cloudmessaging.dgml
  docs/assets/images/cloudmessaging.svg
  docs/assets/images/core.dgml
  docs/concepts/binary-rewriting.md
  docs/get-started/build-source.md
  docs/get-started/install.md
  docs/get-started/using-coyote.md
  docs/how-to/coverage.md
  docs/how-to/liveness-checking.md
  docs/how-to/unit-testing.md
  docs/samples/actors/failover-robot-navigator.md
  docs/samples/actors/failure-detector.md
  docs/samples/tasks/bounded-buffer.md
  docs/tutorials/actors/hello-world.md
  docs/tutorials/actors/raft-azure.md
  docs/tutorials/actors/raft-mocking.md
  docs/tutorials/actors/test-failover.md
  docs/tutorials/first-concurrency-unit-test.md
  docs/tutorials/mocks/mock-dependencies.md
  docs/tutorials/mocks/optimistic-concurrency-control.md
  docs/tutorials/test-concurrent-operations.md
  docs/tutorials/test-failover.md
  docs/tutorials/testing-aspnet-service.md
  global.json
Labels: area-nuget-package

#496 reschedule before AutoResetEvent.Reset
  Source/Test/Rewriting/Types/Threading/EventWaitHandle.cs
  Tests/Tests.BugFinding/Synchronization/AutoResetEventTests.cs
  Tests/compare-rewriting-diff-logs.ps1
Labels: area-systematic-testing

#498 fix github pages deployment
  .github/workflows/publish-docs.yml
Labels: area-documentation

#499 increased version to 1.7.11
  .config/dotnet-tools.json
  CITATION.cff
  Common/version.props
  History.md
  Scripts/encode_nuget_sign_certificate.ps1
  Tests/compare-rewriting-diff-logs.ps1
Labels: area-nuget-package

#500 added link for new website footer requirement
  docs/windmill_dark/footer.html
Labels: area-documentation

#501 edited the new privacy footer link to be a forward link
  docs/windmill_dark/footer.html
Labels: area-documentation

#502 more fixes in the website footer
  docs/windmill_dark/footer.html
Labels: area-documentation

#503 fix website footer spanning
  docs/windmill_dark/footer.html
Labels: area-documentation
